#!/usr/bin/env python3
"""
test_crash.py — what happens if the container dies mid-write?

A child process opens a transaction, writes inside it, does NOT commit, and then
kills itself with SIGKILL — which is exactly what Docker does when it stops a
container the hard way. Then the database is reopened here.

Expected, with no manual intervention: the half-written change is not there, the
database is whole, and history has no ghost version. That last one is the point:
history is written by triggers, so a rolled-back write must leave no trace in
rule_versions either — otherwise the story would record something that never
happened.

Run it with `python3 test_crash.py`. Exit code 0 means green.
"""
from __future__ import annotations

import os
import signal
import subprocess
import sys
import tempfile
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from rules import ALL, Registry

D = tempfile.mkdtemp(prefix="crash-")
DB = os.path.join(D, "rules.db")

R = Registry(DB)
# The code is GENERATED by the registry since v3.0.0: the receipt hands it out.
CODE = R.create_project("Trial", [("architect", "chat")],
                        {"VA": "vault and files"})["code"]
# Filed through the front door, so the ID below is the one the COUNTER handed
# out: VA-0001, because it is the first of its domain.
RID = R.propose(CODE, "VA", "R", "First rule", "Original body.", [ALL],
                reason="setup", proposed_by="architect")["id"]
assert RID == "VA-0001", RID
BASE_VERSIONS = R.history(CODE, RID)["count"]
R.close()

CHILD = textwrap.dedent(f"""
    import os, signal, sys
    sys.path.insert(0, {HERE!r})
    from rules import Registry
    R = Registry({DB!r})
    R.cx.execute("BEGIN IMMEDIATE")
    R.cx.execute("UPDATE rules SET body='BODY NEVER COMMITTED', reason='crash', "
                 "updated_at='2026-01-01T00:00:00Z' "
                 "WHERE project='Trial' AND id='VA-0001'")
    R.cx.execute("INSERT INTO rules (project,id,domain,seq,type,title,body,status,"
                 "reason,updated_at) VALUES ('Trial','VA-9999','VA',9999,'R','ghost',"
                 "'never born','active','crash','2026-01-01T00:00:00Z')")
    sys.stdout.write("written, not committed\\n"); sys.stdout.flush()
    os.kill(os.getpid(), signal.SIGKILL)
""")

p = subprocess.run([sys.executable, "-c", CHILD], capture_output=True, text=True)
print(f"  child said {p.stdout.strip()!r} — signal {-p.returncode} (9 = SIGKILL)")
assert p.returncode == -signal.SIGKILL, p

R2 = Registry(DB)
body = R2.cx.execute("SELECT body FROM rules WHERE id='VA-0001'").fetchone()[0]
ghosts = R2.cx.execute("SELECT COUNT(*) FROM rules WHERE id='VA-9999'").fetchone()[0]
integrity = R2.cx.execute("PRAGMA integrity_check").fetchone()[0]
journal = R2.cx.execute("PRAGMA journal_mode").fetchone()[0]
versions = R2.history(CODE, RID)["count"]
ghost_versions = R2.cx.execute(
    "SELECT COUNT(*) FROM rule_versions WHERE rule_id='VA-9999'").fetchone()[0]

print(f"  body after the crash : {body!r}")
print(f"  ghost rule rows      : {ghosts}")
print(f"  ghost version rows   : {ghost_versions}")
print(f"  integrity_check      : {integrity}")
print(f"  journal_mode         : {journal}")
print(f"  versions in history  : {versions} (was {BASE_VERSIONS})")

assert body == "Original body.", "the uncommitted write survived"
assert ghosts == 0, "a ghost row survived"
assert ghost_versions == 0, "a ghost row left a version behind"
assert integrity == "ok"
assert journal == "wal"
assert versions == BASE_VERSIONS, "a rolled-back write left a version in history"
assert R2.repaired == [], f"the reopen had to repair something: {R2.repaired}"
R2.close()

print("\nOK — rolled back on its own, database whole, history clean.")
